version: '2'
services:
  proxy:
      image: traefik
      command: -c /dev/null --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --configFile=/etc/traefik/conf/acme.toml
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./proxy/certs/oto.vn:/certs
        - ./proxy/traefik.toml:/etc/traefik/conf/acme.toml:ro
        - ./proxy/acme.json:/etc/traefik/conf/acme.json:rw
      labels:
        - "traefik.frontend.rule=Host:monitor.localhost"
        - "traefik.port=8080"
        - "traefik.enable=true"
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=magento2.localhost
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 80
    links:
      - web
  pwa:
    build: gatsby
    ports:
      - 8000
    labels:
      - traefik.backend=pwa_magento23ce
      - 'traefik.frontend.rule=Host:pwa.magento23ce.localhost'
      - traefik.docker.network=proxy
      - traefik.port=8000
    volumes:
      - ../../src/storefront:/site
  web:
    image: 'meanbee/magento2-nginx:1.9'
    ports:
      - '80:80'
    env_file:
      - ./global.env
  fpm:
    image: 'meanbee/magento2-php:7.2-fpm'
    ports:
      - 9000
    env_file:
      - ./global.env
  db:
    image: 'mariadb:10'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh
  cli:
    image: 'meanbee/magento2-php:7.2-cli'
    volumes:
      - '~/.composer/cache:/root/.composer/cache'
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - 'M2SETUP_BASE_URL=http://magento2.localhost/'
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.2.*
  elasticsearch:
    build: elasticsearch
    volumes:
      - ../../data/elasticsearch:/usr/share/elasticsearch/data
    labels:
      - traefik.backend=elasticsearch_magento23ce
      - 'traefik.frontend.rule=Host:elastic.magento23ce.localhost'
      - traefik.port=9200
  kibana:
    image: kibana:6.5.1
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    labels:
      - traefik.backend=elasticsearch_magento23ce
      - 'traefik.frontend.rule=Host:kibana.magento23ce.localhost'
      - traefik.port=9200
  cron:
    image: meanbee/magento2-php:7.2-cli
    hostname: magento2-cron.docker
    command: run-cron
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
  appdata:
    image: tianon/true
    volumes:
      - '../src:/var/www/magento'
      - '../../../extensions/Ecomteck:/var/www/magento/app/code/Ecomteck'
  dbdata:
    image: tianon/true
    volumes:
      - '../data/mysql:/var/lib/mysql'

